import "./globals.css";
import Navbar from'../components/navbar/Navbar.jsx';
import Footer from '../components/footer/Footer.jsx';


export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1366px] min-h-[100vh] md:mx-auto py-0 px-[16px] lg:px-[60px] flex flex-col justify-between">
        <Navbar/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
